[package]
name = "datestamp_files"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4"
walkdir = "2.3"
reqwest = { version = "0.11", features = ["json", "blocking"] }
serde_json = "1.0"
dotenv = "0.15"
clap = {version ="4.5.38", features = ["derive"]}
regex = "1.11.1"
